import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import logo from "./Assets/logo.png";

export default function DashCard() {
  return (
    <>
      <Head>
        <title>Payant/Login</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
     <section className="bg-gray-50 ">
     
  <div className="lg:flex gap-20 items-center justify-center  px-6 py-8 mx-auto  lg:py-0 ">
     
  <div className="w-full  rounded-lg md:mt-0 sm:max-w-md xl:p-0">
          <div className="p-6 space-y-4 md:space-y-4 sm:p-8"> 
          <div className="flex gap-14"> 
        <div className="w-full bg-white rounded-lg shadow dark:border md:mt-0 sm:max-w-md xl:p-0">

          <div className="p-6 space-y-4 md:space-y-4 sm:p-8">
          <div>
            <p>Total Received</p>
          <p className="text-xl font-bold  leading-tight tracking-tight text-purple-700 md:text-2xl ">
              $32,3k
              </p>
              </div>
          </div>
      </div>
      <div className="w-full bg-white rounded-lg shadow dark:border md:mt-0 sm:max-w-md xl:p-0">
          <div className="p-6 space-y-4 md:space-y-4 sm:p-8">
          <div>
            <p>Awaiting Payment</p>
          <p className="text-xl font-bold  leading-tight tracking-tight text-purple-700 text-gray-900 md:text-2xl ">
              $2,055
              </p>
              </div>
          </div>
      </div>
      </div>
      <div className="flex grow gap-14">
      <div className="w-full   bg-white rounded-lg shadow dark:border md:mt-0 sm:max-w-md xl:p-0">
          <div className="p-6 space-y-4 md:space-y-4 sm:p-8">
          <div>
            <p>Awaiting Approval</p>
          <p className="text-xl font-bold  leading-tight tracking-tight text-purple-700 md:text-2xl ">
          $2,055
              </p>
              </div>
          </div>
      </div>
      <div className="w-full  bg-white rounded-lg shadow dark:border md:mt-0 sm:max-w-md xl:p-0">
          <div className="p-6 space-y-4 md:space-y-4 sm:p-8">
          <div>
            <p>Paid Out</p>
          <p className="text-xl font-bold  leading-tight tracking-tight text-purple-700 md:text-2xl ">
          $2,055
              </p>
              </div>
          </div>
      </div> 
      </div> 
          </div>
      </div>
      <div className="w-full mt-5 bg-white  rounded-lg shadow dark:border md:mt-0 sm:max-w-md xl:p-0">
          <div className="p-6 space-y-4 md:space-y-4  sm:p-8">
          <div className="flex justify-between">
          <p className="text-xl font-bold  leading-tight tracking-tight text-gray-900 md:text-2xl ">
              Recent Invoices
              </p>
              <Link href="/Invoice"><button className=" border-2 pr-8 rounded-md pl-8 border-violet-800">Create Invoice</button></Link>
              </div>
              <div className="flex pt-2 justify-between">
                    <p>#1</p>
                    <p>Client Name</p>
                    <p>Status</p>
                    <p>$2,352.00</p>
              </div>
              <div className="flex justify-between">
              <p>#1</p>
                    <p>Client Name</p>
                    <p>Status</p>
                    <p>$2,352.00</p>
              </div>
              <div className="flex justify-between">
              <p>#1</p>
                    <p>Client Name</p>
                    <p>Status</p>
                    <p>$2,352.00</p>
              </div>
              <div className="flex justify-between">
              <p>#1</p>
                    <p>Client Name</p>
                    <p>Status</p>
                    <p>$2,352.00</p>
              </div> 
              </div>
      </div>
  </div>
  <div className="lg:flex gap-20 items-center justify-center  mx-auto ">
  <div className="w-full mt-5 bg-white rounded-lg shadow dark:border md:mt-0 sm:max-w-md xl:p-0">
             <div className="p-6 space-y-4 md:space-y-4 sm:p-8">
             <div className="flex justify-between">
             <p className="text-xl font-bold  leading-tight tracking-tight text-gray-900 md:text-2xl ">
                 Transaction Details
                 </p>
                 <button className=" border-2 pr-8 rounded-md pl-8 border-violet-800">View all</button>
                 </div>
                 <div className="flex pt-2 justify-between">
                    <p>#1</p>
                    <p>Client Name</p>
                    <p>Status</p>
                    <p>$2,352.00</p>
              </div>
              <div className="flex justify-between">
              <p>#1</p>
                    <p>Client Name</p>
                    <p>Status</p>
                    <p>$2,352.00</p>
              </div>
              <div className="flex justify-between">
              <p>#1</p>
                    <p>Client Name</p>
                    <p>Status</p>
                    <p>$2,352.00</p>
              </div>
              <div className="flex justify-between">
              <p>#1</p>
                    <p>Client Name</p>
                    <p>Status</p>
                    <p>$2,352.00</p>
              </div>
                
             </div>
         </div>
     <div className="w-full  rounded-lg md:mt-0 sm:max-w-md  xl:p-0">
             <div className="p-6 space-y-4 md:space-y-4 sm:p-8"> 
             <div className="flex gap-14"> 
           <div className="w-full bg-white rounded-lg shadow dark:border md:mt-0 sm:max-w-md xl:p-0">
   
             <div className="p-6 space-y-4 md:space-y-4 sm:p-8">
             <div>
             <p className="text-xl font-bold  leading-tight tracking-tight text-gray-900 md:text-2xl ">
                 Dashboard
                 </p>
                 </div>
             </div>
         </div>
        </div>
         
             </div>
         </div>
         
     </div>
</section>
      
    </>
  )
}