import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import logo from "./Assets/logo.png";
import 'reactjs-popup/dist/index.css';
import Popup from 'reactjs-popup';
import { ToastContainer, toast } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';


export default function SetCard() {
      const notify = () => toast.success("Password Changed!");
  function handlesubmit() {
    notify();
    close();
  }
  return (
    <>
      <Head>
        <title>Payant/Login</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
     <section className="bg-gray-50 ">
     
  <div className="lg:flex gap-20 items-center justify-center px-6 py-8 mx-auto md:h-screen lg:py-0">
     
  <div className="w-full bg-white rounded-lg shadow dark:border md:mt-0 sm:max-w-md xl:p-0">
          <div className="p-6 space-y-4 md:space-y-4 sm:p-8">
          <div className="flex justify-between">
          <p className="text-xl font-bold  leading-tight tracking-tight text-gray-900 md:text-2xl ">
              Personal Details
              </p>
              <Popup
    trigger={<button className="border-2 pr-8 p-1 hover:text-white hover:bg-indigo-600 rounded-md pl-8 border-indigo-600">Edit</button>}
    modal

  >
    {close => (
      <div className="modal">
        <button className="close" onClick={close}>
          &times;
        </button>
        <div className="content">
        <div className="">
          <div className="p-6 space-y-2 ">
              <p className="text-lg font-bold text-center leading-tight tracking-tight text-gray-900 md:text-2xl ">
                  Add Client
              </p>
              <form className="space-y-4 md:space-y-4" >
                 <div>
                      <input type="name" name="name" id="name" className=" border border-gray-300 text-black sm:text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:placeholder-gray-400  dark:focus:ring-blue-500 dark:focus:border-blue-500" placeholder="Full Name" required />
                  </div>
                  <div>
                      <input type="number" name="name" id="name" className=" border border-gray-300 text-black sm:text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:placeholder-gray-400  dark:focus:ring-blue-500 dark:focus:border-blue-500" placeholder="Phone Number" required />
                  </div>
                  <div>
                      <input type="email" name="email" id="email" className=" border border-gray-300 text-black sm:text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5  dark:placeholder-gray-400  dark:focus:ring-blue-500 dark:focus:border-blue-500" placeholder="Email Address" required />
                  </div>
                  <div>
                      <input type="address" name="address" id="address" className=" border border-gray-300 text-black sm:text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5  dark:placeholder-gray-400  dark:focus:ring-blue-500 dark:focus:border-blue-500" placeholder="Address" required />
                  </div>
                  <div>
                      <input type="name" name="name" id="name" className=" border border-gray-300 text-black sm:text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5  dark:placeholder-gray-400  dark:focus:ring-blue-500 dark:focus:border-blue-500" placeholder="City" required />
                  </div>
                  <div>
                      <input type="name" name="name" id="name" className=" border border-gray-300 text-black sm:text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5  dark:placeholder-gray-400  dark:focus:ring-blue-500 dark:focus:border-blue-500" placeholder="Country" required />
                  </div>
             <button onClick={handlesubmit}  className="w-full font-medium rounded-lg text-sm px-5 py-2.5 text-center hover:text-white hover:bg-indigo-600 border-2 pr-8  pl-8 border-indigo-600">Save Changes</button>
             <ToastContainer />
             </form>   
          </div>
      </div>
       
      </div>
      </div>
    )}
  </Popup>
              
              </div>
            
              <div className="flex justify-between">
                    <p>First Name</p>
                    <p>XXXX</p>
              </div>
              <div className="flex justify-between">
                    <p>First Name</p>
                    <p>XXXX</p>
              </div>
              <div className="flex justify-between">
                    <p>First Name</p>
                    <p>XXXX</p>
              </div>
              <div className="flex justify-between">
                    <p>First Name</p>
                    <p>XXXX</p>
              </div>
              <Link href="#">    <button type="submit" className="w-full mt-4 text-white bg-primary-600 hover:bg-primary-700 focus:ring-4 focus:outline-none focus:ring-primary-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-primary-700 dark:focus:ring-primary-800">Save</button></Link>
          </div>
      </div>
      <div className="w-full mt-5 bg-white rounded-lg shadow dark:border md:mt-0 sm:max-w-md xl:p-0">
          <div className="p-6 space-y-4 md:space-y-4 sm:p-8">
          <div className="flex justify-between">
          <p className="text-xl font-bold  leading-tight tracking-tight text-gray-900 md:text-2xl ">
              Bussiness Details
              </p>
              <Popup
    trigger={<button className="border-2 pr-8 p-1 hover:text-white hover:bg-indigo-600 rounded-md pl-8 border-indigo-600">Edit</button>}
    modal

  >
    {close => (
      <div className="modal">
        <button className="close" onClick={close}>
          &times;
        </button>
        <div className="content">
        <div className="">
          <div className="p-6 space-y-2 ">
              <p className="text-lg font-bold text-center leading-tight tracking-tight text-gray-900 md:text-2xl ">
                  Add Client
              </p>
              <form className="space-y-4 md:space-y-4" >
                 <div>
                      <input type="name" name="name" id="name" className=" border border-gray-300 text-black sm:text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:placeholder-gray-400  dark:focus:ring-blue-500 dark:focus:border-blue-500" placeholder="Bussiness Name" required />
                  </div>
                  <div>
                      <input type="address" name="address" id="address" className=" border border-gray-300 text-black sm:text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5  dark:placeholder-gray-400  dark:focus:ring-blue-500 dark:focus:border-blue-500" placeholder="Address" required />
                  </div>
                  <div>
                      <input type="address" name="address" id="address" className=" border border-gray-300 text-black sm:text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5  dark:placeholder-gray-400  dark:focus:ring-blue-500 dark:focus:border-blue-500" placeholder="Address" required />
                  </div>
                  <div>
                      <input type="name" name="name" id="name" className=" border border-gray-300 text-black sm:text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5  dark:placeholder-gray-400  dark:focus:ring-blue-500 dark:focus:border-blue-500" placeholder="City" required />
                  </div>
                  <div>
                      <input type="name" name="name" id="name" className=" border border-gray-300 text-black sm:text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5  dark:placeholder-gray-400  dark:focus:ring-blue-500 dark:focus:border-blue-500" placeholder="Country" required />
                  </div>
                  <div>
                      <input type="name" name="name" id="name" className=" border border-gray-300 text-black sm:text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5  dark:placeholder-gray-400  dark:focus:ring-blue-500 dark:focus:border-blue-500" placeholder="Country" required />
                  </div> 
             <button onClick={handlesubmit}  className="w-full font-medium rounded-lg text-sm px-5 py-2.5 text-center hover:text-white hover:bg-indigo-600 border-2 pr-8  pl-8 border-indigo-600">Save Changes</button>
             <ToastContainer />
             </form>   
          </div>
      </div>
       
      </div>
      </div>
    )}
  </Popup>
              </div>
              <div className="flex justify-between">
                    <p>First Name</p>
                    <p>XXXX</p>
              </div>
              <div className="flex justify-between">
                    <p>First Name</p>
                    <p>XXXX</p>
              </div>
              <div className="flex justify-between">
                    <p>First Name</p>
                    <p>XXXX</p>
              </div>
              <div className="flex justify-between">
                    <p>First Name</p>
                    <p>XXXX</p>
              </div>
              <Link href="#">    <button type="submit" className="w-full mt-4 text-white bg-primary-600 hover:bg-primary-700 focus:ring-4 focus:outline-none focus:ring-primary-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-primary-700 dark:focus:ring-primary-800">Save</button></Link>
          </div>
      </div>
  </div>
</section>
      
    </>
  )
}