import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import logo from "./Assets/logo.png";

export default function SetCard() {
  return (
    <>
      <Head>
        <title>Payant/Login</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
     <section className="bg-gray-50 ">
     
  <div className="lg:flex gap-20 items-center justify-center px-6 py-8 mx-auto md:h-screen lg:py-0">
     
  <div className="w-full bg-white rounded-lg shadow dark:border md:mt-0 sm:max-w-md xl:p-0">
          <div className="p-6 space-y-4 md:space-y-4 sm:p-8">
          <div className="flex justify-between">
          <p className="text-xl font-bold  leading-tight tracking-tight text-gray-900 md:text-2xl ">
              Personal Details
              </p>
              <button className=" border-2 pr-8 rounded-md pl-8 border-violet-800">Edit</button>
              </div>
            
              <div className="flex justify-between">
                    <p>First Name</p>
                    <p>XXXX</p>
              </div>
              <div className="flex justify-between">
                    <p>First Name</p>
                    <p>XXXX</p>
              </div>
              <div className="flex justify-between">
                    <p>First Name</p>
                    <p>XXXX</p>
              </div>
              <div className="flex justify-between">
                    <p>First Name</p>
                    <p>XXXX</p>
              </div>
              <Link href="#">    <button type="submit" className="w-full mt-4 text-white bg-primary-600 hover:bg-primary-700 focus:ring-4 focus:outline-none focus:ring-primary-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-primary-700 dark:focus:ring-primary-800">Save</button></Link>
          </div>
      </div>
      <div className="w-full mt-5 bg-white rounded-lg shadow dark:border md:mt-0 sm:max-w-md xl:p-0">
          <div className="p-6 space-y-4 md:space-y-4 sm:p-8">
          <div className="flex justify-between">
          <p className="text-xl font-bold  leading-tight tracking-tight text-gray-900 md:text-2xl ">
              Bussiness Details
              </p>
              <button className=" border-2 pr-8 rounded-md pl-8 border-violet-800">Edit</button>
              </div>
              <div className="flex justify-between">
                    <p>First Name</p>
                    <p>XXXX</p>
              </div>
              <div className="flex justify-between">
                    <p>First Name</p>
                    <p>XXXX</p>
              </div>
              <div className="flex justify-between">
                    <p>First Name</p>
                    <p>XXXX</p>
              </div>
              <div className="flex justify-between">
                    <p>First Name</p>
                    <p>XXXX</p>
              </div>
              <Link href="#">    <button type="submit" className="w-full mt-4 text-white bg-primary-600 hover:bg-primary-700 focus:ring-4 focus:outline-none focus:ring-primary-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-primary-700 dark:focus:ring-primary-800">Save</button></Link>
          </div>
      </div>
  </div>
</section>
      
    </>
  )
}